default_context:
  project_name: 'Fast Apps'
  project_slug: 'fast-apps'
  domain_main: 'fast-apps.com'
  domain_staging: 'stag.fast-apps.com'
  docker_swarm_stack_name_main: 'fast-apps-com'
  docker_swarm_stack_name_staging: 'stag-fast-apps-com'
  secret_key: '37ba24193f2ec33c27c2277a4282cecb2ff94b4eff6c1e7b4e909a8ab8bc47a0'
  first_superuser: 'admin@fast-apps.com'
  first_superuser_password: 'fast123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fast-apps.com", "https://stag.fast-apps.com", "https://fast-apps.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fast-apps.com'
  postgres_password: '200551fc52632440257526854ba084eab5784b3375b91f672d8afe29eab0127d'
  pgadmin_default_user: 'admin@fast-apps.com'
  pgadmin_default_user_password: 'fast123'
  traefik_constraint_tag: 'fast-apps.com'
  traefik_constraint_tag_staging: 'stag.fast-apps.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:fast123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
